## Actividad 3_14
<div style="border-style:groove;border-width:thin;padding:10px">
Debes hacer lo siguiente:
    <ol>
        <li>Soluciona MNIST usando KMeans. Usa X_train y deja X_test e y_test guardados. Recuerda, no tienes que usar las etiquetas para nada.</li>
        <li>Muestra primeras imágenes de la clase 0, 1, 2, 3, 4, etc. ¿Qué tal lo ha hecho?</li>
        <li>Los centroides son datos de 784 valores. Pinta los 10 centroides como si fueran imágenes.</li>
        <li>Piensa como sacar una métrica del resultado.</li>
    </ol>
</div>

In [6]:
from sklearn.datasets import make_moons
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import matplotlib.pyplot as plt

from sklearn.tree import export_graphviz
from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, silhouette_score

In [7]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)
mnist.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [8]:
X, y = mnist["data"], mnist["target"]
print(X.shape)
print(y.shape)

(70000, 784)
(70000,)


In [15]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=1000)
kmeans.fit_predict(X)
print(kmeans.labels_)
print(kmeans.cluster_centers_)
print(kmeans.inertia_)
#print(silhouette_score(X, kmeans.labels_)) 178464532118.78928

[735 718  74 ...  99 604  46]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
92320858295.30894
